package org.whilmarbitoco.core.database;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for dialect detection and SQL generation differences.
 */
class DialectTest {

    @Test
    @DisplayName("fromUrl detects MySQL")
    void detectMySQL() {
        Dialect d = Dialect.fromUrl("jdbc:mysql://localhost:3306/test");
        assertInstanceOf(MySQLDialect.class, d);
        assertEquals("mysql", d.name());
    }

    @Test
    @DisplayName("fromUrl detects PostgreSQL")
    void detectPostgreSQL() {
        Dialect d = Dialect.fromUrl("jdbc:postgresql://localhost:5432/test");
        assertInstanceOf(PostgreSQLDialect.class, d);
        assertEquals("postgresql", d.name());
    }

    @Test
    @DisplayName("fromUrl detects SQLite")
    void detectSQLite() {
        Dialect d = Dialect.fromUrl("jdbc:sqlite:test.db");
        assertInstanceOf(SQLiteDialect.class, d);
        assertEquals("sqlite", d.name());
    }

    @Test
    @DisplayName("fromName works for all dialects")
    void fromName() {
        assertInstanceOf(MySQLDialect.class, Dialect.fromName("mysql"));
        assertInstanceOf(MySQLDialect.class, Dialect.fromName("mariadb"));
        assertInstanceOf(PostgreSQLDialect.class, Dialect.fromName("postgresql"));
        assertInstanceOf(PostgreSQLDialect.class, Dialect.fromName("postgres"));
        assertInstanceOf(SQLiteDialect.class, Dialect.fromName("sqlite"));
    }

    @Test
    @DisplayName("fromUrl throws for unknown database")
    void unknownDbThrows() {
        assertThrows(IllegalArgumentException.class, () -> Dialect.fromUrl("jdbc:oracle:thin:@localhost:1521:test"));
    }

    @Test
    @DisplayName("Identifier quoting differs per dialect")
    void identifierQuoting() {
        assertEquals("`users`", new MySQLDialect().quoteIdentifier("users"));
        assertEquals("\"users\"", new PostgreSQLDialect().quoteIdentifier("users"));
        assertEquals("\"users\"", new SQLiteDialect().quoteIdentifier("users"));
    }

    @Test
    @DisplayName("Auto-increment SQL differs per dialect")
    void autoIncrement() {
        assertEquals("AUTO_INCREMENT", new MySQLDialect().autoIncrement());
        assertEquals("GENERATED BY DEFAULT AS IDENTITY", new PostgreSQLDialect().autoIncrement());
        assertEquals("AUTOINCREMENT", new SQLiteDialect().autoIncrement());
    }

    @Test
    @DisplayName("Integer PK type differs per dialect")
    void integerPKType() {
        assertEquals("INT", new MySQLDialect().integerPKType());
        assertEquals("INTEGER", new PostgreSQLDialect().integerPKType());
        assertEquals("INTEGER", new SQLiteDialect().integerPKType());
    }

    @Test
    @DisplayName("String type differs per dialect")
    void stringType() {
        assertEquals("VARCHAR(255)", new MySQLDialect().resolveType(String.class));
        assertEquals("VARCHAR(255)", new PostgreSQLDialect().resolveType(String.class));
        assertEquals("TEXT", new SQLiteDialect().resolveType(String.class));
    }

    @Test
    @DisplayName("Boolean type differs per dialect")
    void booleanType() {
        assertEquals("TINYINT(1)", new MySQLDialect().resolveType(boolean.class));
        assertEquals("BOOLEAN", new PostgreSQLDialect().resolveType(boolean.class));
        assertEquals("INTEGER", new SQLiteDialect().resolveType(boolean.class));
    }

    @Test
    @DisplayName("LIMIT/OFFSET syntax differs per dialect")
    void limitOffsetSyntax() {
        assertEquals("LIMIT 10, 20", new MySQLDialect().limitOffset(20, 10));
        assertEquals("LIMIT 20 OFFSET 10", new PostgreSQLDialect().limitOffset(20, 10));
        assertEquals("LIMIT 20 OFFSET 10", new SQLiteDialect().limitOffset(20, 10));
    }

    @Test
    @DisplayName("Table engine clause differs per dialect")
    void tableEngine() {
        assertEquals("ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", new MySQLDialect().tableEngine());
        assertEquals("", new PostgreSQLDialect().tableEngine());
        assertEquals("", new SQLiteDialect().tableEngine());
    }

    @Test
    @DisplayName("Migration table DDL differs per dialect")
    void migrationsTableDDL() {
        String mysql = new MySQLDialect().createMigrationsTable("schema_migrations");
        assertTrue(mysql.contains("INT PRIMARY KEY"));
        assertTrue(mysql.contains("ENGINE=InnoDB"));

        String pg = new PostgreSQLDialect().createMigrationsTable("schema_migrations");
        assertTrue(pg.contains("INTEGER PRIMARY KEY"));
        assertFalse(pg.contains("ENGINE"));

        String sqlite = new SQLiteDialect().createMigrationsTable("schema_migrations");
        assertTrue(sqlite.contains("INTEGER PRIMARY KEY"));
        assertTrue(sqlite.contains("datetime"));
    }
}
