package org.whilmarbitoco.core.database;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for dialect-aware MigrationGenerator.
 */
class MigrationGeneratorDialectTest {

    @Table(name = "test_users")
    static class TestUser {
        @Primary @Column(name = "id") private int id;
        @Column(name = "name") private String name;
        @Column(name = "active") private boolean active;
    }

    @Table(name = "test_posts")
    static class TestPost {
        @Primary @Column(name = "id") private int id;
        @Column(name = "title") private String title;
        @Column(name = "user_id") private int userId;
        @BelongsTo(foreignKey = "user_id", referencedTable = "test_users", referencedColumn = "id")
        private TestUser user;
    }

    @Test
    @DisplayName("MySQL dialect generates correct CREATE TABLE")
    void mysqlCreateTable() {
        Dialect dialect = new MySQLDialect();
        String sql = MigrationGenerator.generateCreateTable(dialect, TestUser.class);

        assertTrue(sql.contains("CREATE TABLE IF NOT EXISTS `test_users`"));
        assertTrue(sql.contains("`id` INT NOT NULL AUTO_INCREMENT"));
        assertTrue(sql.contains("`name` VARCHAR(255) NOT NULL"));
        assertTrue(sql.contains("`active` TINYINT(1)"));
        assertTrue(sql.contains("PRIMARY KEY (`id`)"));
        assertTrue(sql.contains("ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"));
    }

    @Test
    @DisplayName("PostgreSQL dialect generates correct CREATE TABLE")
    void postgresCreateTable() {
        Dialect dialect = new PostgreSQLDialect();
        String sql = MigrationGenerator.generateCreateTable(dialect, TestUser.class);

        assertTrue(sql.contains("CREATE TABLE IF NOT EXISTS \"test_users\""));
        assertTrue(sql.contains("\"id\" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY"));
        assertTrue(sql.contains("\"name\" VARCHAR(255) NOT NULL"));
        assertTrue(sql.contains("\"active\" BOOLEAN"));
        assertTrue(sql.contains("PRIMARY KEY (\"id\")"));
        assertFalse(sql.contains("ENGINE="));
    }

    @Test
    @DisplayName("SQLite dialect generates correct CREATE TABLE")
    void sqliteCreateTable() {
        Dialect dialect = new SQLiteDialect();
        String sql = MigrationGenerator.generateCreateTable(dialect, TestUser.class);

        assertTrue(sql.contains("CREATE TABLE IF NOT EXISTS \"test_users\""));
        assertTrue(sql.contains("\"id\" INTEGER NOT NULL AUTOINCREMENT"));
        assertTrue(sql.contains("\"name\" TEXT NOT NULL"));
        assertTrue(sql.contains("\"active\" INTEGER"));
        assertTrue(sql.contains("PRIMARY KEY (\"id\")"));
        assertFalse(sql.contains("ENGINE="));
    }

    @Test
    @DisplayName("MySQL dialect generates FK constraint for @BelongsTo")
    void mysqlForeignKey() {
        Dialect dialect = new MySQLDialect();
        String sql = MigrationGenerator.generateCreateTable(dialect, TestPost.class);

        assertTrue(sql.contains("FOREIGN KEY (`user_id`)"));
        assertTrue(sql.contains("REFERENCES `test_users` (`id`)"));
        assertTrue(sql.contains("ON DELETE CASCADE"));
        assertTrue(sql.contains("INDEX"));
    }

    @Test
    @DisplayName("PostgreSQL dialect generates FK constraint for @BelongsTo")
    void postgresForeignKey() {
        Dialect dialect = new PostgreSQLDialect();
        String sql = MigrationGenerator.generateCreateTable(dialect, TestPost.class);

        assertTrue(sql.contains("FOREIGN KEY (\"user_id\")"));
        assertTrue(sql.contains("REFERENCES \"test_users\" (\"id\")"));
        assertTrue(sql.contains("ON DELETE CASCADE"));
    }

    @Test
    @DisplayName("SQLite dialect generates FK constraint for @BelongsTo")
    void sqliteForeignKey() {
        Dialect dialect = new SQLiteDialect();
        String sql = MigrationGenerator.generateCreateTable(dialect, TestPost.class);

        assertTrue(sql.contains("FOREIGN KEY (\"user_id\")"));
        assertTrue(sql.contains("REFERENCES \"test_users\" (\"id\")"));
        assertTrue(sql.contains("ON DELETE CASCADE"));
    }

    @Test
    @DisplayName("Generated SQL includes dialect name in comment")
    void dialectComment() {
        assertTrue(MigrationGenerator.generateCreateTable(new MySQLDialect(), TestUser.class).contains("-- Auto-generated by MigrationGenerator (mysql)"));
        assertTrue(MigrationGenerator.generateCreateTable(new PostgreSQLDialect(), TestUser.class).contains("-- Auto-generated by MigrationGenerator (postgresql)"));
        assertTrue(MigrationGenerator.generateCreateTable(new SQLiteDialect(), TestUser.class).contains("-- Auto-generated by MigrationGenerator (sqlite)"));
    }
}
