package org.whilmarbitoco.core.database;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for MigrationGenerator.
 */
class MigrationGeneratorTest {

    // ── Test models ───────────────────────────────────────────────

    @Table(name = "test_users")
    static class TestUser {
        @Primary
        @Column(name = "id")
        private int id;
        @Column(name = "name")
        private String name;
        @Column(name = "email")
        private String email;
    }

    @Table(name = "test_posts")
    static class TestPost {
        @Primary
        @Column(name = "id")
        private int id;
        @Column(name = "title")
        private String title;
        @Column(name = "user_id")
        private int userId;
        @BelongsTo(foreignKey = "user_id", referencedTable = "test_users", referencedColumn = "id")
        private TestUser user;
    }

    @Table(name = "test_tags")
    static class TestTag {
        @Primary
        @Column(name = "id")
        private int id;
        @Column(name = "label")
        private String label;
    }

    @Test
    @DisplayName("generateCreateTable produces correct SQL for simple entity")
    void generateSimpleTable() {
        String sql = MigrationGenerator.generateCreateTable(TestUser.class);

        assertTrue(sql.contains("CREATE TABLE IF NOT EXISTS test_users"));
        assertTrue(sql.contains("id INT NOT NULL AUTO_INCREMENT"));
        assertTrue(sql.contains("name VARCHAR(255) NOT NULL"));
        assertTrue(sql.contains("email VARCHAR(255) NOT NULL"));
        assertTrue(sql.contains("PRIMARY KEY (id)"));
        assertTrue(sql.contains("ENGINE=InnoDB"));
    }

    @Test
    @DisplayName("generateCreateTable includes FK constraint for @BelongsTo")
    void generateTableWithForeignKey() {
        String sql = MigrationGenerator.generateCreateTable(TestPost.class);

        assertTrue(sql.contains("CREATE TABLE IF NOT EXISTS test_posts"));
        assertTrue(sql.contains("title VARCHAR(255) NOT NULL"));
        assertTrue(sql.contains("user_id INT"));
        assertTrue(sql.contains("FOREIGN KEY (user_id)"));
        assertTrue(sql.contains("REFERENCES test_users (id)"));
        assertTrue(sql.contains("ON DELETE CASCADE"));
        assertTrue(sql.contains("INDEX idx_test_posts_user_id (user_id)"));
    }

    @Test
    @DisplayName("generateCreateTable skips @HasMany fields (List relationships)")
    void generateTableSkipsHasMany() {
        // TestUser doesn't have @HasMany, but verify no List fields appear
        String sql = MigrationGenerator.generateCreateTable(TestUser.class);
        assertFalse(sql.contains("todos"));
        assertFalse(sql.contains("List"));
    }

    @Test
    @DisplayName("generateCreateTable handles String columns as NOT NULL")
    void stringColumnsAreNotNull() {
        String sql = MigrationGenerator.generateCreateTable(TestTag.class);
        assertTrue(sql.contains("label VARCHAR(255) NOT NULL"));
    }

    @Test
    @DisplayName("generate writes migration files to output directory")
    void generateWritesFiles(@TempDir File tempDir) throws IOException {
        // We can't easily test package scanning without the classes being on the classpath,
        // but we can test the file writing by calling generateCreateTable directly
        // and verifying the output format.
        String sql = MigrationGenerator.generateCreateTable(TestUser.class);
        assertNotNull(sql);
        assertTrue(sql.startsWith("-- Auto-generated by MigrationGenerator"));
    }

    @Test
    @DisplayName("generated SQL is syntactically complete (ends with semicolon)")
    void sqlEndsWithSemicolon() {
        String sql = MigrationGenerator.generateCreateTable(TestUser.class);
        assertTrue(sql.trim().endsWith(";"));
    }

    @Test
    @DisplayName("generated SQL includes charset utf8mb4")
    void sqlIncludesCharset() {
        String sql = MigrationGenerator.generateCreateTable(TestUser.class);
        assertTrue(sql.contains("utf8mb4"));
    }
}
