package org.whilmarbitoco.core.database;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Field;
import java.util.*;

/**
 * Generates SQL migration files by introspecting entity classes.
 * Dialect-aware — generates the correct SQL for MySQL, PostgreSQL, or SQLite.
 *
 * Usage:
 * <pre>
 *   // Auto-detect dialect from config:
 *   MigrationGenerator.generate("org.whilmarbitoco.database.model", "src/main/resources/migrations");
 *
 *   // Or specify a dialect:
 *   MigrationGenerator.generate(Dialect.fromName("sqlite"), "org.whilmarbitoco.database.model", "src/main/resources/migrations");
 * </pre>
 */
public class MigrationGenerator {

    /**
     * Generate migration files using the dialect auto-detected from config.dbUrl().
     */
    public static void generate(String packageName, String outputDir) throws IOException {
        Dialect dialect = Dialect.fromUrl(org.whilmarbitoco.core.utils.Config.dbUrl());
        generate(dialect, packageName, outputDir);
    }

    /**
     * Generate migration files using the specified dialect.
     */
    public static void generate(Dialect dialect, String packageName, String outputDir) throws IOException {
        List<Class<?>> entities = scanPackage(packageName);
        if (entities.isEmpty()) {
            System.out.println("[MigrationGenerator] No entity classes found in " + packageName);
            return;
        }

        // Sort: tables without FK dependencies first
        entities.sort((a, b) -> {
            boolean aHasFk = hasForeignKey(a);
            boolean bHasFk = hasForeignKey(b);
            return Boolean.compare(aHasFk, bHasFk);
        });

        File dir = new File(outputDir);
        if (!dir.exists()) dir.mkdirs();

        int version = nextVersion(dir);
        for (Class<?> entity : entities) {
            String sql = generateCreateTable(dialect, entity);
            String tableName = getTableName(entity);
            String filename = "V" + version + "__create_" + tableName + "_table.sql";
            File file = new File(dir, filename);

            try (FileWriter writer = new FileWriter(file)) {
                writer.write(sql);
            }

            System.out.println("[MigrationGenerator] Generated " + filename);
            version++;
        }
    }

    /**
     * Generate the CREATE TABLE SQL for a single entity class using the given dialect.
     */
    public static String generateCreateTable(Dialect dialect, Class<?> type) {
        String tableName = getTableName(type);
        StringBuilder sb = new StringBuilder();
        sb.append("-- Auto-generated by MigrationGenerator (").append(dialect.name()).append(")\n");
        sb.append(dialect.createTableIfNotExists(tableName)).append(" (\n");

        List<String> columns = new ArrayList<>();
        List<String> constraints = new ArrayList<>();
        List<String> indexes = new ArrayList<>();

        for (Field field : type.getDeclaredFields()) {
            if (field.isAnnotationPresent(HasMany.class)) continue;
            if (isRelationshipObjectField(field, dialect)) continue;

            Primary primary = field.getAnnotation(Primary.class);
            Column column = field.getAnnotation(Column.class);
            BelongsTo belongsTo = field.getAnnotation(BelongsTo.class);

            if (primary != null && column != null) {
                // Primary key: use dialect-specific type and auto-increment
                String pkType = field.getType() == long.class || field.getType() == Long.class
                        ? dialect.longPKType() : dialect.integerPKType();
                String colDef = "  " + dialect.quoteIdentifier(column.name()) + " " + pkType
                        + " NOT NULL " + dialect.autoIncrement();
                columns.add(colDef);
                constraints.add("  PRIMARY KEY (" + dialect.quoteIdentifier(column.name()) + ")");
            } else if (column != null) {
                String colDef = "  " + dialect.quoteIdentifier(column.name()) + " " + dialect.resolveType(field.getType());
                if (field.getType() == String.class) {
                    colDef += " NOT NULL";
                }
                columns.add(colDef);

                if (belongsTo != null) {
                    String fkName = "fk_" + tableName + "_" + column.name();
                    constraints.add("  " + dialect.foreignKeyConstraint(
                            fkName, column.name(),
                            belongsTo.referencedTable(), belongsTo.referencedColumn()));
                    indexes.add("  " + dialect.createIndex(
                            "idx_" + tableName + "_" + column.name(),
                            tableName, column.name()));
                }
            }
        }

        sb.append(String.join(",\n", columns));
        if (!constraints.isEmpty()) {
            sb.append(",\n").append(String.join(",\n", constraints));
        }
        if (!indexes.isEmpty()) {
            sb.append(",\n").append(String.join(",\n", indexes));
        }

        String engine = dialect.tableEngine();
        if (engine != null && !engine.isEmpty()) {
            sb.append("\n) ").append(engine).append(";\n");
        } else {
            sb.append("\n);\n");
        }

        return sb.toString();
    }

    // ── Helpers ──────────────────────────────────────────────────

    private static String getTableName(Class<?> type) {
        Table table = type.getAnnotation(Table.class);
        if (table == null) throw new RuntimeException("Class " + type.getName() + " is not annotated with @Table");
        return table.name();
    }

    private static boolean isRelationshipObjectField(Field field, Dialect dialect) {
        // Skip List<Child> (handled by @HasMany)
        if (field.getType() == java.util.List.class) return true;
        // Skip object references that aren't mapped by the dialect's type map
        if (!field.getType().isPrimitive() && !dialect.typeMap().containsKey(field.getType()) && !field.getType().isEnum()) {
            // If it has @BelongsTo, the FK column is already handled above
            // If it's an object without @Column, skip it
            return field.getAnnotation(Column.class) == null;
        }
        return false;
    }

    private static boolean hasForeignKey(Class<?> type) {
        for (Field field : type.getDeclaredFields()) {
            if (field.isAnnotationPresent(BelongsTo.class)) return true;
        }
        return false;
    }

    private static int nextVersion(File dir) {
        File[] files = dir.listFiles((d, name) -> name.matches("V\\d+__.*\\.sql"));
        if (files == null || files.length == 0) return 1;
        int max = 0;
        for (File f : files) {
            try {
                String num = f.getName().substring(1, f.getName().indexOf("__"));
                max = Math.max(max, Integer.parseInt(num));
            } catch (NumberFormatException e) { /* skip */ }
        }
        return max + 1;
    }

    private static List<Class<?>> scanPackage(String packageName) {
        List<Class<?>> result = new ArrayList<>();
        String path = packageName.replace('.', '/');
        try {
            var resources = MigrationGenerator.class.getClassLoader().getResources(path);
            while (resources.hasMoreElements()) {
                var url = resources.nextElement();
                if ("file".equals(url.getProtocol())) {
                    File dir = new File(url.toURI());
                    scanDir(dir, packageName, result);
                }
            }
        } catch (Exception e) {
            throw new RuntimeException("[MigrationGenerator] Failed to scan package " + packageName + ": " + e.getMessage(), e);
        }
        return result;
    }

    private static void scanDir(File dir, String packageName, List<Class<?>> result) {
        File[] files = dir.listFiles();
        if (files == null) return;
        for (File file : files) {
            if (file.isDirectory()) {
                scanDir(file, packageName + "." + file.getName(), result);
            } else if (file.getName().endsWith(".class")) {
                String className = packageName + "." + file.getName().replace(".class", "");
                try {
                    Class<?> clazz = Class.forName(className);
                    if (clazz.isAnnotationPresent(Table.class)) {
                        result.add(clazz);
                    }
                } catch (ClassNotFoundException e) { /* skip */ }
            }
        }
    }
}
