package org.whilmarbitoco.core.database;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Field;
import java.util.*;

/**
 * Generates SQL migration files by introspecting entity classes.
 *
 * Scans a given package for classes annotated with {@link Table},
 * reads their {@link Column}, {@link Primary}, {@link HasMany}, and {@link BelongsTo}
 * annotations, and produces CREATE TABLE statements with:
 *   - Proper column types (inferred from Java types)
 *   - PRIMARY KEY constraints
 *   - FOREIGN KEY constraints (from @HasMany / @BelongsTo)
 *   - NOT NULL constraints (for non-nullable columns)
 *   - Indexes on foreign key columns
 *
 * Usage:
 * <pre>
 *   MigrationGenerator.generate("org.whilmarbitoco.database.model", "src/main/resources/migrations");
 *   // Creates V1__create_users_table.sql, V2__create_todos_table.sql, etc.
 * </pre>
 *
 * The generated files follow the naming convention: V{version}__{description}.sql
 * and can be applied with {@link MigrationRunner}.
 */
public class MigrationGenerator {

    /** Maps Java types to MySQL column types. */
    private static final Map<Class<?>, String> TYPE_MAP = Map.ofEntries(
            Map.entry(int.class, "INT"),
            Map.entry(Integer.class, "INT"),
            Map.entry(long.class, "BIGINT"),
            Map.entry(Long.class, "BIGINT"),
            Map.entry(float.class, "FLOAT"),
            Map.entry(Float.class, "FLOAT"),
            Map.entry(double.class, "DOUBLE"),
            Map.entry(Double.class, "DOUBLE"),
            Map.entry(boolean.class, "TINYINT(1)"),
            Map.entry(Boolean.class, "TINYINT(1)"),
            Map.entry(String.class, "VARCHAR(255)"),
            Map.entry(java.sql.Date.class, "DATE"),
            Map.entry(java.sql.Time.class, "TIME"),
            Map.entry(java.sql.Timestamp.class, "TIMESTAMP")
    );

    /**
     * Generate migration files for all entity classes in the given package.
     *
     * @param packageName  the package to scan (e.g. "org.whilmarbitoco.database.model")
     * @param outputDir    the directory to write SQL files to (e.g. "src/main/resources/migrations")
     */
    public static void generate(String packageName, String outputDir) throws IOException {
        List<Class<?>> entities = scanPackage(packageName);
        if (entities.isEmpty()) {
            System.out.println("[MigrationGenerator] No entity classes found in " + packageName);
            return;
        }

        // Sort: tables without FK dependencies first, then dependent tables
        entities.sort((a, b) -> {
            boolean aHasFk = hasForeignKey(a);
            boolean bHasFk = hasForeignKey(b);
            return Boolean.compare(aHasFk, bHasFk);
        });

        File dir = new File(outputDir);
        if (!dir.exists()) dir.mkdirs();

        int version = nextVersion(dir);
        for (Class<?> entity : entities) {
            String sql = generateCreateTable(entity);
            String tableName = getTableName(entity);
            String filename = "V" + version + "__create_" + tableName + "_table.sql";
            File file = new File(dir, filename);

            try (FileWriter writer = new FileWriter(file)) {
                writer.write(sql);
            }

            System.out.println("[MigrationGenerator] Generated " + filename);
            version++;
        }
    }

    /**
     * Generate the CREATE TABLE SQL for a single entity class.
     */
    public static String generateCreateTable(Class<?> type) {
        String tableName = getTableName(type);
        StringBuilder sb = new StringBuilder();
        sb.append("-- Auto-generated by MigrationGenerator\n");
        sb.append("CREATE TABLE IF NOT EXISTS ").append(tableName).append(" (\n");

        List<String> columns = new ArrayList<>();
        List<String> constraints = new ArrayList<>();
        List<String> indexes = new ArrayList<>();

        for (Field field : type.getDeclaredFields()) {
            // Skip relationship fields (List<Child> or ParentType)
            if (field.isAnnotationPresent(HasMany.class)) continue;
            if (isRelationshipField(field)) continue;

            Primary primary = field.getAnnotation(Primary.class);
            Column column = field.getAnnotation(Column.class);
            BelongsTo belongsTo = field.getAnnotation(BelongsTo.class);

            if (primary != null && column != null) {
                // Primary key column
                String colDef = "  " + column.name() + " " + resolveType(field.getType())
                        + " NOT NULL AUTO_INCREMENT";
                columns.add(colDef);
                constraints.add("  PRIMARY KEY (" + column.name() + ")");
            } else if (column != null) {
                // Regular column
                String colDef = "  " + column.name() + " " + resolveType(field.getType());
                // String columns are NOT NULL by default, others nullable
                if (field.getType() == String.class) {
                    colDef += " NOT NULL";
                }
                columns.add(colDef);

                // If this field also has @BelongsTo, add FK constraint and index
                if (belongsTo != null) {
                    String fkName = "fk_" + tableName + "_" + column.name();
                    constraints.add("  CONSTRAINT " + fkName
                            + " FOREIGN KEY (" + column.name() + ")"
                            + " REFERENCES " + belongsTo.referencedTable()
                            + " (" + belongsTo.referencedColumn() + ")"
                            + " ON DELETE CASCADE");
                    indexes.add("  INDEX idx_" + tableName + "_" + column.name()
                            + " (" + column.name() + ")");
                }
            }
        }

        // Build the full statement
        sb.append(String.join(",\n", columns));
        if (!constraints.isEmpty()) {
            sb.append(",\n").append(String.join(",\n", constraints));
        }
        if (!indexes.isEmpty()) {
            sb.append(",\n").append(String.join(",\n", indexes));
        }
        sb.append("\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n");

        return sb.toString();
    }

    // ── Helpers ───────────────────────────────────────────────────

    private static String getTableName(Class<?> type) {
        Table table = type.getAnnotation(Table.class);
        if (table == null) throw new RuntimeException("Class " + table + " is not annotated with @Table");
        return table.name();
    }

    private static String resolveType(Class<?> javaType) {
        String sqlType = TYPE_MAP.get(javaType);
        if (sqlType != null) return sqlType;
        // Default fallback
        if (javaType.isEnum()) return "VARCHAR(50)";
        return "VARCHAR(255)";
    }

    private static boolean isRelationshipField(Field field) {
        // List<Child> for @HasMany
        if (field.getType() == java.util.List.class) return true;
        // Object reference for @BelongsTo (not a primitive or standard type)
        if (!field.getType().isPrimitive()
                && !TYPE_MAP.containsKey(field.getType())
                && !field.getType().isEnum()
                && field.getType().getPackageName().startsWith("java.")) {
            return true;
        }
        return false;
    }

    private static boolean hasForeignKey(Class<?> type) {
        for (Field field : type.getDeclaredFields()) {
            if (field.isAnnotationPresent(BelongsTo.class)) return true;
        }
        return false;
    }

    private static int nextVersion(File dir) {
        File[] files = dir.listFiles((d, name) -> name.matches("V\\d+__.*\\.sql"));
        if (files == null || files.length == 0) return 1;
        int max = 0;
        for (File f : files) {
            try {
                String num = f.getName().substring(1, f.getName().indexOf("__"));
                max = Math.max(max, Integer.parseInt(num));
            } catch (NumberFormatException e) { /* skip */ }
        }
        return max + 1;
    }

    /**
     * Scan a package for classes annotated with @Table.
     * Uses classpath scanning — works for file-based and jar-based deployments.
     */
    private static List<Class<?>> scanPackage(String packageName) {
        List<Class<?>> result = new ArrayList<>();
        String path = packageName.replace('.', '/');
        try {
            var resources = MigrationGenerator.class.getClassLoader().getResources(path);
            while (resources.hasMoreElements()) {
                var url = resources.nextElement();
                if ("file".equals(url.getProtocol())) {
                    File dir = new File(url.toURI());
                    scanDir(dir, packageName, result);
                }
            }
        } catch (Exception e) {
            throw new RuntimeException("[MigrationGenerator] Failed to scan package " + packageName + ": " + e.getMessage(), e);
        }
        return result;
    }

    private static void scanDir(File dir, String packageName, List<Class<?>> result) {
        File[] files = dir.listFiles();
        if (files == null) return;
        for (File file : files) {
            if (file.isDirectory()) {
                scanDir(file, packageName + "." + file.getName(), result);
            } else if (file.getName().endsWith(".class")) {
                String className = packageName + "." + file.getName().replace(".class", "");
                try {
                    Class<?> clazz = Class.forName(className);
                    if (clazz.isAnnotationPresent(Table.class)) {
                        result.add(clazz);
                    }
                } catch (ClassNotFoundException e) {
                    // skip
                }
            }
        }
    }
}
