package org.whilmarbitoco.core.database;

import java.util.Map;

/**
 * PostgreSQL dialect.
 */
public class PostgreSQLDialect implements Dialect {

    @Override public String name() { return "postgresql"; }
    @Override public String driverClass() { return "org.postgresql.Driver"; }
    @Override public String urlPrefix() { return "jdbc:postgresql://"; }

    @Override public String autoIncrement() { return "GENERATED BY DEFAULT AS IDENTITY"; }
    @Override public String integerPKType() { return "INTEGER"; }
    @Override public String longPKType() { return "BIGINT"; }

    @Override
    public String resolveType(Class<?> javaType) {
        return typeMap().getOrDefault(javaType, "VARCHAR(255)");
    }

    @Override
    public Map<Class<?>, String> typeMap() {
        return Map.ofEntries(
                Map.entry(int.class, "INTEGER"),
                Map.entry(Integer.class, "INTEGER"),
                Map.entry(long.class, "BIGINT"),
                Map.entry(Long.class, "BIGINT"),
                Map.entry(float.class, "REAL"),
                Map.entry(Float.class, "REAL"),
                Map.entry(double.class, "DOUBLE PRECISION"),
                Map.entry(Double.class, "DOUBLE PRECISION"),
                Map.entry(boolean.class, "BOOLEAN"),
                Map.entry(Boolean.class, "BOOLEAN"),
                Map.entry(String.class, "VARCHAR(255)"),
                Map.entry(java.sql.Date.class, "DATE"),
                Map.entry(java.sql.Time.class, "TIME"),
                Map.entry(java.sql.Timestamp.class, "TIMESTAMP")
        );
    }

    @Override public String quoteIdentifier(String id) { return "\"" + id + "\""; }

    @Override
    public String limitOffset(int limit, int offset) {
        return "LIMIT " + limit + " OFFSET " + offset;
    }

    @Override
    public String limit(int limit) {
        return "LIMIT " + limit;
    }

    @Override public String tableEngine() { return ""; }

    @Override
    public String createTableIfNotExists(String tableName) {
        return "CREATE TABLE IF NOT EXISTS " + quoteIdentifier(tableName);
    }

    @Override
    public String createMigrationsTable(String tableName) {
        return "CREATE TABLE IF NOT EXISTS " + quoteIdentifier(tableName) + " ("
                + quoteIdentifier("version") + " INTEGER PRIMARY KEY, "
                + quoteIdentifier("applied_at") + " TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                + ")";
    }

    @Override
    public String checkMigrationVersion(String tableName, int version) {
        return "SELECT 1 FROM " + quoteIdentifier(tableName)
                + " WHERE " + quoteIdentifier("version") + " = " + version;
    }

    @Override
    public String insertMigrationVersion(String tableName, int version) {
        return "INSERT INTO " + quoteIdentifier(tableName)
                + " (" + quoteIdentifier("version") + ") VALUES (" + version + ")";
    }

    @Override public String onDeleteCascade() { return "ON DELETE CASCADE"; }

    @Override
    public String foreignKeyConstraint(String constraintName, String column,
                                        String referencedTable, String referencedColumn) {
        return "CONSTRAINT " + quoteIdentifier(constraintName)
                + " FOREIGN KEY (" + quoteIdentifier(column) + ")"
                + " REFERENCES " + quoteIdentifier(referencedTable)
                + " (" + quoteIdentifier(referencedColumn) + ")"
                + " " + onDeleteCascade();
    }

    @Override
    public String createIndex(String indexName, String tableName, String column) {
        return "CREATE INDEX IF NOT EXISTS " + quoteIdentifier(indexName)
                + " ON " + quoteIdentifier(tableName)
                + " (" + quoteIdentifier(column) + ")";
    }
}
