-- Auto-generated by MigrationGenerator (sqlite)
CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER NOT NULL AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  PRIMARY KEY ("id")
);
