-- Auto-generated by MigrationGenerator (sqlite)
CREATE TABLE IF NOT EXISTS "todos" (
  "id" INTEGER NOT NULL AUTOINCREMENT,
  "todo" TEXT NOT NULL,
  "user_id" INTEGER,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
  CREATE INDEX IF NOT EXISTS "idx_todos_user_id" ON "todos" ("user_id")
);
